"""Mathematics element specs."""

from ..registry import ElementSpec, FieldSpec

ELEMENT_SPECS: list[ElementSpec] = [
    ElementSpec(
        name="fraction_model",
        subjects=["math"],
        synopsis="shape: circle|bar|grid, total_parts, shaded_parts, color, label",
        fields=[
            FieldSpec("shape", type="string", required=False, default="circle",
                      enum=["circle", "bar", "grid"],
                      description="Visual representation style"),
            FieldSpec("total_parts", type="integer", required=True,
                      description="Total number of equal parts"),
            FieldSpec("shaded_parts", type="integer", required=True,
                      description="Number of shaded (coloured) parts"),
            FieldSpec("color", type="color", required=False, default="green"),
            FieldSpec("label", type="string", required=False,
                      description="Caption below the model; defaults to 'shaded/total'"),
        ],
    ),
    ElementSpec(
        name="bar_model",
        subjects=["math"],
        synopsis="bars: [{label, value, color}], difference: {label, color} (optional)",
        fields=[
            FieldSpec("bars", type="array", required=True,
                      description="Comparison bars — list of bar dicts",
                      items=FieldSpec("bar", type="object", properties=[
                          FieldSpec("label", type="string",
                                    description="Bar label; include units here e.g. 'Friend A = $5.00'"),
                          FieldSpec("value", type="number",
                                    constraint="MUST be a plain number — WRONG: \"$5.00\"  RIGHT: 5"),
                          FieldSpec("color", type="color"),
                      ])),
            FieldSpec("difference", type="object", required=False,
                      description="Bracket showing the gap between two bars",
                      properties=[
                          FieldSpec("label", type="string"),
                          FieldSpec("color", type="color"),
                      ]),
        ],
        notes=["IMPORTANT: bar value MUST be a plain number, not a formatted string."],
    ),
    ElementSpec(
        name="coordinate_plane",
        subjects=["math"],
        synopsis="x_range, y_range, grid_step, plots: [{type, equation|coord, color}]",
        fields=[
            FieldSpec("x_range", type="array", required=True,
                      description="[min, max] for the x-axis"),
            FieldSpec("y_range", type="array", required=True,
                      description="[min, max] for the y-axis"),
            FieldSpec("grid_step", type="integer", required=False, default=1,
                      description="Grid line interval"),
            FieldSpec("plots", type="array", required=False,
                      description="List of line or point plot specs",
                      items=FieldSpec("plot", type="object", properties=[
                          FieldSpec("type", type="string", enum=["line", "point"]),
                          FieldSpec("equation", type="string", required=False,
                                    description="Linear equation e.g. 'y=2x+1' (line only)"),
                          FieldSpec("coord", type="array", required=False,
                                    description="[x, y] coordinate (point only)"),
                          FieldSpec("label", type="string", required=False),
                          FieldSpec("color", type="color", required=False),
                      ])),
        ],
    ),
    ElementSpec(
        name="geometry_shape",
        subjects=["math"],
        synopsis="vertices: [[x,y],...], labels, side_labels, angles — polygon with annotations",
        fields=[
            FieldSpec("vertices", type="array", required=True,
                      description="List of [x, y] coordinate pairs defining the polygon"),
            FieldSpec("labels", type="array", required=False,
                      description="Vertex label strings or {text, position, offset, anchor} dicts (one per vertex)"),
            FieldSpec("side_labels", type="array", required=False,
                      description="[{edge: 'AB', label: '5 cm'}] — label for each named edge",
                      items=FieldSpec("sl", type="object", properties=[
                          FieldSpec("edge", type="string",
                                    description="Two-letter vertex pair e.g. 'AB'"),
                          FieldSpec("label", type="string",
                                    description="Text shown at the midpoint of the edge"),
                      ])),
            FieldSpec("angles", type="array", required=False,
                      description="[{vertex: 'A', arc: true, label: '90°'}] — angle annotations",
                      items=FieldSpec("ang", type="object", properties=[
                          FieldSpec("vertex", type="string",
                                    description="Vertex label where the angle sits"),
                          FieldSpec("sides", type="array", required=False,
                                    description="Optional list of two vertex labels specifying custom bounding sides for the angle (useful for external angles)"),
                          FieldSpec("arc", type="any", required=False,
                                    description="Draw arc if true (defaults to square for 90° angles); use 'square' to force square right-angle indicator"),
                          FieldSpec("label", type="string", required=False,
                                    description="Angle measure label e.g. '90°'"),
                      ])),
            FieldSpec("edges", type="array", required=False,
                      description="Optional list of edge connections between vertex labels (e.g. ['AB', 'BC'] or [['A', 'B']]). If specified, renders separate lines instead of a single closed polygon."),
        ],
    ),
    ElementSpec(
        name="factor_array",
        subjects=["math"],
        synopsis="number: N — draws N as a dot rectangle (concrete->pictorial for factors/primes)",
        fields=[
            FieldSpec("number", type="integer", required=True,
                      description="The whole number to represent as a dot array"),
            FieldSpec("rows", type="integer", required=False,
                      description="Override row count; omit to auto-pick most-square factor pair"),
            FieldSpec("cols", type="integer", required=False,
                      description="Override column count; must be paired with rows"),
            FieldSpec("caption", type="string", required=False,
                      description="Label below array; defaults to 'N = rows × cols'"),
            FieldSpec("color", type="color", required=False, default="green"),
            FieldSpec("verdict", type="boolean", required=False, default=False,
                      description="If true, adds 'Prime / Composite / neither' label"),
        ],
        notes=[
            "PREFER factor_array over example_panel whenever a slide teaches factors or primes.",
            "verdict: true adds an automatic Prime / Composite / neither label.",
        ],
    ),
    ElementSpec(
        name="math_grid",
        subjects=["math"],
        synopsis="rows: [[cells],...], headers: [strings] — column arithmetic or ratio grid",
        fields=[
            FieldSpec("mode", type="string", required=False, default="arithmetic",
                      enum=["arithmetic", "ratio"],
                      description="'arithmetic' (default) for column place-value grids with operators; "
                                  "'ratio' for ratio tables showing A : B (: C …) per row with colon separators"),
            FieldSpec("rows", type="array", required=True,
                      description="List of rows; each row is a list of cell values. "
                                  "In arithmetic mode, the string 'line' draws a separator. "
                                  "To render an operator (e.g. +, -), place it as the first cell of the row (e.g. ['+', '2', '0'])."),
            FieldSpec("headers", type="array", required=False,
                      description="Optional column header labels"),
            FieldSpec("row_colors", type="array", required=False,
                      description="Per-row color names (same length as data rows)"),
            FieldSpec("show_grid", type="boolean", required=False, default=True,
                      description="If true (default), draws grid boxes around digit cells in arithmetic mode. If false, hides the boxes but keeps alignment."),
        ],
        notes=[
            "In arithmetic mode, place the operator (+, -, ×, ÷) as the first cell of the operator row (e.g. ['+', '2', '0']) so that it renders next to the digits without a border box.",
        ],
    ),
    ElementSpec(
        name="fraction_equation",
        subjects=["math"],
        synopsis="terms: [strings|objects] — horizontal math equation featuring vertical fractions",
        fields=[
            FieldSpec("terms", type="array", required=True,
                      description="List of terms in the equation. Each term can be a string (e.g. '1/5', '+', '3/5', '=', '4/5', '2 1/5') "
                                  "or an object with properties: val, color, bold, placeholder"),
        ],
    ),
    ElementSpec(
        name="solid_shape",
        subjects=["math"],
        synopsis="shape: cube|rectangular_prism|triangular_prism|pyramid|cone|cylinder, dimensions, color, label",
        fields=[
            FieldSpec("shape", type="string", required=False, default="cube",
                      enum=["cube", "rectangular_prism", "triangular_prism", "pyramid", "cone", "cylinder"],
                      description="3D shape type"),
            FieldSpec("dimensions", type="array", required=False, default=[3, 3, 3],
                      description="[width, height, depth] — if 1 value given, used for all; if 2 given, third defaults to second"),
            FieldSpec("color", type="color", required=False, default="blue"),
            FieldSpec("label", type="string", required=False,
                      description="Measurement label below the shape (e.g. '5 cm' or '5×3×2 cm³')"),
            FieldSpec("show_dimensions", type="boolean", required=False, default=False,
                      description="If true, renders dimension measurements on the shape (radius, height, etc.)"),
        ],
        notes=[
            "All shapes use isometric projection for consistent 3D perspective.",
            "Dimensions are auto-scaled to fit the content zone.",
            "For a cube, pass dimensions: [side] or dimensions: [5].",
            "For a rectangular prism, pass dimensions: [width, height, depth].",
            "show_dimensions: true renders radius/height labels for cones and cylinders, useful for volume/surface area lessons.",
        ],
    ),
]
